### PR TITLE
Banner titles

### PR DESCRIPTION
**Pull request by LostPaul**
image

# New/Edited features

- Command to add a title to a note
- Command to remove the title
- Edit title by clicking on it
- Embed support
- Slower dragging of the banner image
- Below and next to icon placement support

# Bug fixes

### Old
https://user-images.githubusercontent.com/70213368/210142632-095cb27a-3911-44f8-beeb-c02d0c5f4a40.mp4

### New
https://user-images.githubusercontent.com/70213368/210142862-eec09a2b-0b1f-4ad1-ae88-439173f55251.mp4

### Old
https://user-images.githubusercontent.com/70213368/210148435-f17c0a1a-fdc2-45ee-b238-ea63d7a77287.mp4

### New
https://user-images.githubusercontent.com/70213368/210148539-fd2a573b-acda-4d0b-a6c4-135972aae71c.mp4

### CODE REVIEW

**Comment by DevBOFH** [comment]
👍 Would love to see this get merged.

**Comment by LucEast** [comment]
Yo Bro, I don't think that the owner of this plugin still develop it. 
Maybe publish your own community plugin of this version. 
We need someone who actively commits and updates.

**Comment by mariomui** [comment]
i disagree with not having a proper dist folder for pumping out to distribution. is this obsidian requirement to pump out artifacts into root?

**Comment by noatpad** [comment]
Closing this PR due to the complete 2.0 rewrite. Pardon me that I didn't get the chance to review and see if this can be merged before, but as I did the rewrite, I took into consideration your banner title implementation for the "headers" part of v2, so thank you very much for your contribution to add those headers into Banners

**Pull request closed without merging**
